/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as DecisionRoomRouteImport } from './routes/decision-room'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ApiInvestigationsRouteImport } from './routes/api.investigations'
import { Route as InvestigationsIndexRouteImport } from './routes/investigations.index'
import { Route as InvestigationsInvestigationIdRouteImport } from './routes/investigations.$investigationId'
import { Route as ApiVoiceSessionRouteImport } from './routes/api.voice.session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoomRoute = DecisionRoomRouteImport.update({
  id: '/decision-room',
  path: '/decision-room',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvestigationsRoute = ApiInvestigationsRouteImport.update({
  id: '/api/investigations',
  path: '/api/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIndexRoute = InvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsInvestigationIdRoute =
  InvestigationsInvestigationIdRouteImport.update({
    id: '/investigations/$investigationId',
    path: '/investigations/$investigationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiVoiceSessionRoute = ApiVoiceSessionRouteImport.update({
  id: '/api/voice/session',
  path: '/api/voice/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/decision-room': typeof DecisionRoomRoute
  '/decisions': typeof DecisionsRoute
  '/integrations': typeof IntegrationsRoute
  '/api/investigations': typeof ApiInvestigationsRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/api/voice/session': typeof ApiVoiceSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/decision-room': typeof DecisionRoomRoute
  '/decisions': typeof DecisionsRoute
  '/integrations': typeof IntegrationsRoute
  '/api/investigations': typeof ApiInvestigationsRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/api/voice/session': typeof ApiVoiceSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/decision-room': typeof DecisionRoomRoute
  '/decisions': typeof DecisionsRoute
  '/integrations': typeof IntegrationsRoute
  '/api/investigations': typeof ApiInvestigationsRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/api/voice/session': typeof ApiVoiceSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/decision-room'
    | '/decisions'
    | '/integrations'
    | '/api/investigations'
    | '/investigations/$investigationId'
    | '/investigations/'
    | '/api/voice/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/decision-room'
    | '/decisions'
    | '/integrations'
    | '/api/investigations'
    | '/investigations/$investigationId'
    | '/investigations'
    | '/api/voice/session'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/decision-room'
    | '/decisions'
    | '/integrations'
    | '/api/investigations'
    | '/investigations/$investigationId'
    | '/investigations/'
    | '/api/voice/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DecisionRoomRoute: typeof DecisionRoomRoute
  DecisionsRoute: typeof DecisionsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  ApiInvestigationsRoute: typeof ApiInvestigationsRoute
  InvestigationsInvestigationIdRoute: typeof InvestigationsInvestigationIdRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
  ApiVoiceSessionRoute: typeof ApiVoiceSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision-room': {
      id: '/decision-room'
      path: '/decision-room'
      fullPath: '/decision-room'
      preLoaderRoute: typeof DecisionRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/investigations': {
      id: '/api/investigations'
      path: '/api/investigations'
      fullPath: '/api/investigations'
      preLoaderRoute: typeof ApiInvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof InvestigationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$investigationId': {
      id: '/investigations/$investigationId'
      path: '/investigations/$investigationId'
      fullPath: '/investigations/$investigationId'
      preLoaderRoute: typeof InvestigationsInvestigationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/session': {
      id: '/api/voice/session'
      path: '/api/voice/session'
      fullPath: '/api/voice/session'
      preLoaderRoute: typeof ApiVoiceSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DecisionRoomRoute: DecisionRoomRoute,
  DecisionsRoute: DecisionsRoute,
  IntegrationsRoute: IntegrationsRoute,
  ApiInvestigationsRoute: ApiInvestigationsRoute,
  InvestigationsInvestigationIdRoute: InvestigationsInvestigationIdRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
  ApiVoiceSessionRoute: ApiVoiceSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
